Repository Survival-Cartel/photopin, pull requests merged in 2025-05, with the labels that each got.

#40 #38 map_filter 생성
  lib/presentation/component/map_filter.dart
  test/presentation/component/map_filter_test.dart
Labels: feature

#43 #39 map_bottom_sheet 컴포넌트
  lib/core/extensions/datetime_extension.dart
  lib/presentation/component/map_bottom_sheet.dart
  test/presentation/component/map_bottom_sheet_test.dart
Labels: feature

#48 #45 feat compare card
  lib/core/extensions/datetime_extension.dart
  lib/presentation/component/compare_card.dart
  test/presentation/component/compare_card_test.dart
Labels: feature

#41 #36 bottom_bar
  lib/presentation/component/bottom_bar.dart
  test/presentation/component/bottom_bar_test.dart
Labels: feature

#49 #46 notification card 컴포넌트
  lib/core/extensions/datetime_extension.dart
  lib/core/styles/app_color.dart
  lib/presentation/component/notification_card.dart
  test/presentation/component/notification_card_test.dart
Labels: feature

#50 #42 feat recent activity tile
  lib/core/extensions/datetime_extension.dart
  lib/presentation/component/recent_activity_tile.dart
  test/presentation/component/recent_activity_tile_test.dart
Labels: feature

#56 #47 feat map
  android/app/src/main/AndroidManifest.xml
  lib/presentation/component/photopin_map.dart
  pubspec.lock
  pubspec.yaml
  test/presentation/component/photo_map_test.dart
Labels: feature

#59 refactor: analize 후 const 붙여주기기
  test/presentation/component/photo_map_test.dart
Labels: refactor

#62 #61 feat user model
  .gitignore
  README.md
  analysis_options.yaml
  lib/user/data/dto/user_dto.dart
  lib/user/data/mapper/user_mapper.dart
  lib/user/domain/model/user_model.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feature

#65 #64 feat photo model
  README.md
  lib/photo/data/dto/photo_dto.dart
  lib/photo/data/mapper/photo_mapper.dart
  lib/photo/domain/model/photo_model.dart
Labels: feature

#71 #70 journal 모델 구현
  lib/journal/data/dto/journal_dto.dart
  lib/journal/data/mapper/journal_mapper.dart
  lib/journal/domain/model/journal_model.dart
Labels: feature

#81 #77 feat search bar
  lib/presentation/component/search_bar.dart
  test/presentation/component/search_bar_test.dart
Labels: feature

#85 #78 feat alert share link
  lib/presentation/component/alert_share_link.dart
  test/presentation/component/alert_share_link_test.dart
Labels: feature

#90 #89 refactor model class freezed delete
  .github/workflows/flutter.yaml
  lib/journal/data/dto/journal_dto.dart
  lib/journal/data/mapper/journal_mapper.dart
  lib/journal/domain/model/journal_model.dart
  lib/location/data/dto/location_dto.dart
  lib/location/domain/model/location_model.dart
  lib/photo/data/dto/photo_dto.dart
  lib/photo/domain/model/photo_model.dart
  lib/user/data/dto/user_dto.dart
  lib/user/domain/model/user_model.dart
  pubspec.yaml
  test/widget_test.dart
Labels: refactor

#86 #80 refactor journey card
  analysis_options.yaml
  lib/location/domain/model/location_model.dart
  lib/presentation/component/journal_card.dart
  lib/presentation/component/journal_card_image.dart
  test/presentation/component/journey_card_image_test.dart
  test/presentation/component/journey_card_test.dart
Labels: refactor

#91 #76 edit bottom sheet 컴포넌트 구현
  lib/presentation/component/edit_bottom_sheet.dart
  lib/presentation/component/text_limit_input_field.dart
  test/presentation/component/edit_bottom_sheet_test.dart
Labels: feature

#99 #97 derry scripts
  pubspec.lock
  pubspec.yaml
Labels: feature

#103 #101 user 데이터 소스 구현
  lib/core/firebase/firestore_setup.dart
  lib/user/data/data_source/user_data_source.dart
  lib/user/data/data_source/user_data_source_impl.dart
  lib/user/data/dto/user_dto.dart
  pubspec.lock
  test/user/data/data_source/fake_user_data_source.dart
  test/user/data/data_source/user_data_source_test.dart
Labels: feature

#105 #104 feat: static timout func create
  lib/core/firebase/firestore_timeout.dart
Labels: feature

#108 #102 feat journal data source create
  lib/core/firebase/firestore_setup.dart
  lib/journal/data/data_source/journal_data_source.dart
  lib/journal/data/data_source/journal_data_source_impl.dart
  lib/journal/data/dto/journal_dto.dart
  lib/journal/data/mapper/journal_mapper.dart
  lib/journal/domain/model/journal_model.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  test/journal/data/data_source/fake_journal_data_source.dart
  test/journal/data/data_source/journal_data_source_test.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feature

#110 refactor: journal field 변경으로 인한 오류 코드 수정
  lib/presentation/component/journal_card.dart
  test/presentation/component/journey_card_test.dart
Labels: refactor

#117 #113 User Repository 구현
  lib/core/data/repository.dart
  lib/core/di/di_setup.dart
  lib/user/data/repository/user_repository.dart
  lib/user/data/repository/user_repository_impl.dart
  test/user/data/data_source/mock_user_data_source.dart
  test/user/data/repository/user_repository_test.dart
  test/user/fixtures/user_dto_fixtures.dart
Labels: feature

#121 test: user data source 테스트 코드 리팩터링
  test/user/data/data_source/user_data_source_test.dart
Labels: refactor

#127 #126 각 model class 에 copyWith 추가
  lib/journal/domain/model/journal_model.dart
  lib/photo/domain/model/photo_model.dart
  lib/user/domain/model/user_model.dart
Labels: refactor

#125 #122 feat auth data source repository
  lib/auth/data/data_source/auth_data_source.dart
  lib/auth/data/data_source/auth_data_source_impl.dart
  lib/auth/data/repository/auth_repository.dart
  lib/auth/data/repository/auth_repository_impl.dart
  lib/core/di/di_setup.dart
  lib/user/data/mapper/user_mapper.dart
  pubspec.yaml
  test/auth/data/data_source/auth_data_source_test.dart
  test/auth/data/data_source/fake_auth_data_source.dart
  test/auth/data/repository/auth_repository_test.dart
  test/auth/fixtures/auth_data_fixtures.dart
Labels: feature

#130 #114 feat journal repository
  lib/core/di/di_setup.dart
  lib/journal/data/mapper/journal_mapper.dart
  lib/journal/data/repository/journal_repository.dart
  lib/journal/data/repository/journal_repository_impl.dart
  test/journal/data/repository/journal_repository_test.dart
  test/journal/fixtures/journal_dto_fixtures.dart
  test/journal/fixtures/journal_model_fixtures.dart
Labels: feature

#131 #129 feat auth screen create
  lib/auth/data/data_source/auth_data_source.dart
  lib/auth/data/data_source/auth_data_source_impl.dart
  lib/auth/data/repository/auth_repository.dart
  lib/auth/data/repository/auth_repository_impl.dart
  lib/core/di/di_setup.dart
  lib/main_dev.dart
  lib/presentation/screen/auth/auth_action.dart
  lib/presentation/screen/auth/auth_screen.dart
  lib/presentation/screen/auth/auth_screen_root.dart
  lib/presentation/screen/auth/auth_state.dart
  lib/presentation/screen/auth/auth_view_model.dart
  test/auth/data/data_source/fake_auth_data_source.dart
  test/presentation/screen/auth/auth_view_model.dart
Labels: feature

#132 #124 Journal Screen
  lib/core/di/di_setup.dart
  lib/core/usecase/get_journal_list_use_case.dart
  lib/presentation/component/journal_card.dart
  lib/presentation/screen/journal/journal_screen.dart
  lib/presentation/screen/journal/journal_screen_action.dart
  lib/presentation/screen/journal/journal_screen_root.dart
  lib/presentation/screen/journal/journal_screen_state.dart
  lib/presentation/screen/journal/journal_screen_view_model.dart
  pubspec.lock
  pubspec.yaml
  test/journal/fixtures/journal_model_fixtures.dart
  test/journal/screen/journal_screen_view_model_test.dart
  test/presentation/component/journal_card_image_test.dart
  test/presentation/component/journal_card_test.dart
Labels: feature

#134 #128 go router 적용
  lib/core/router.dart
  lib/core/routes.dart
  lib/main_dev.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#141 #140 refactor model dto datetime type chane int milliseconds
  lib/core/usecase/get_journal_list_use_case.dart
  lib/journal/data/dto/journal_dto.dart
  lib/journal/data/mapper/journal_mapper.dart
  lib/journal/domain/model/journal_model.dart
  lib/photo/data/dto/photo_dto.dart
  lib/photo/data/mapper/photo_mapper.dart
  lib/photo/domain/model/photo_model.dart
  lib/presentation/screen/home/home_screen.dart
  test/journal/data/data_source/journal_data_source_test.dart
  test/journal/fixtures/journal_dto_fixtures.dart
  test/journal/fixtures/journal_model_fixtures.dart
  test/photo/data/data_source/photo_data_source_test.dart
  test/photo/fixtures/photo_dto_fixtures.dart
  test/photo/fixtures/photo_model_fixtures.dart
  test/presentation/component/journal_card_test.dart
Labels: refactor

#142 #135 feat main screen
  lib/core/router.dart
  lib/presentation/component/bottom_bar.dart
  lib/presentation/component/top_bar.dart
  lib/presentation/screen/main/main_screen.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  test/presentation/component/bottom_bar_test.dart
  test/presentation/component/top_bar_test.dart
Labels: feature

#144 #136 Journal Repository 연동 및 홈 스크린 연동
  lib/core/di/di_setup.dart
  lib/core/router.dart
  lib/core/routes.dart
  lib/core/usecase/get_journal_list_use_case.dart
  lib/journal/data/dto/journal_dto.dart
  lib/journal/data/repository/journal_repository.dart
  lib/presentation/screen/auth/auth_screen.dart
  lib/presentation/screen/auth/auth_state.dart
  lib/presentation/screen/auth/auth_view_model.dart
  lib/presentation/screen/home/home_screen.dart
  lib/presentation/screen/home/home_screen_root.dart
  lib/presentation/screen/home/home_state.dart
  lib/presentation/screen/home/home_view_model.dart
  lib/presentation/screen/journal/journal_screen_root.dart
  lib/presentation/screen/journal/journal_screen_view_model.dart
  test/journal/screen/journal_screen_view_model_test.dart
  test/presentation/screen/auth/auth_view_model_test.dart
  test/presentation/screen/home/home_view_model_test.dart
Labels: feature

#151 #145 refactor shellroute mainscreen 로직 수정
  lib/core/router.dart
  lib/core/routes.dart
  lib/main_dev.dart
  saved-data/auth_export/accounts.json
  saved-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  saved-data/firestore_export/all_namespaces/all_kinds/output-0
  saved-data/firestore_export/firestore_export.overall_export_metadata
Labels: refactor

#149 #148 firestore 데이터 변경
  saved-data/auth_export/accounts.json
  saved-data/firebase-export-metadata.json
  saved-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  saved-data/firestore_export/all_namespaces/all_kinds/output-0
  saved-data/firestore_export/firestore_export.overall_export_metadata
Labels: feature

#152 #138 feat map screen
  README.md
  ios/Podfile.lock
  lib/core/di/di_setup.dart
  lib/core/extensions/datetime_extension.dart
  lib/core/router.dart
  lib/core/routes.dart
  lib/journal/data/dto/journal_dto.dart
  lib/photo/data/data_source/photo_data_source_impl.dart
  lib/photo/data/dto/photo_dto.dart
  lib/photo/data/repository/photo_repository.dart
  lib/photo/data/repository/photo_repository_impl.dart
  lib/presentation/component/date_range_slider.dart
  lib/presentation/component/photopin_map.dart
  lib/presentation/component/timeline_tile.dart
  lib/presentation/screen/journal/journal_screen_root.dart
  lib/presentation/screen/map/map_action.dart
  lib/presentation/screen/map/map_screen.dart
  lib/presentation/screen/map/map_screen_root.dart
  lib/presentation/screen/map/map_state.dart
  lib/presentation/screen/map/map_view_model.dart
  pubspec.lock
  pubspec.yaml
  saved-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  saved-data/firestore_export/all_namespaces/all_kinds/output-0
  saved-data/firestore_export/firestore_export.overall_export_metadata
  test/photo/data/repository/photo_repository_test.dart
  test/presentation/component/range_slider_test.dart
  test/presentation/component/timeline_tile_test.dart
Labels: feature

#155 #154 Hotfix Router 수정
  lib/core/router.dart
  lib/presentation/screen/home/home_screen_root.dart
Labels: hotfix

#159 #157 feat home screen modify
  lib/core/di/di_setup.dart
  lib/core/router.dart
  lib/presentation/screen/home/home_action.dart
  lib/presentation/screen/home/home_screen.dart
  lib/presentation/screen/home/home_screen_root.dart
  lib/presentation/screen/home/home_state.dart
  lib/presentation/screen/home/home_view_model.dart
  test/presentation/screen/home/home_view_model_test.dart
Labels: refactor

#164 #163 feat new journal modal create
  lib/core/di/di_setup.dart
  lib/presentation/component/new_journal_modal.dart
  lib/presentation/component/photopin_head.dart
  lib/presentation/component/text_chip.dart
  lib/presentation/component/text_limit_input_field.dart
  lib/presentation/component/top_bar.dart
  lib/presentation/component/trip_with_chips.dart
  lib/presentation/screen/home/home_action.dart
  lib/presentation/screen/home/home_screen.dart
  lib/presentation/screen/home/home_screen_root.dart
  lib/presentation/screen/home/home_view_model.dart
  lib/presentation/screen/journal/journal_screen.dart
  lib/presentation/screen/map/map_screen.dart
  test/presentation/screen/home/home_view_model_test.dart
Labels: feature

#165 #158 camera 기능 일부분
  android/app/src/main/AndroidManifest.xml
  firebase_device.json
  lib/core/router.dart
  lib/core/routes.dart
  lib/main_dev.dart
  lib/presentation/screen/camera/camera_launcher_screen.dart
  lib/presentation/screen/main/main_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#161 # 160-refactor-main-screen-profile-modify
  lib/core/di/di_setup.dart
  lib/core/router.dart
  lib/presentation/screen/home/home_screen_root.dart
  lib/presentation/screen/main/main_screen.dart
  lib/presentation/screen/main/main_screen_root.dart
  lib/presentation/screen/main/main_state.dart
  lib/presentation/screen/main/main_view_model.dart
Labels: refactor

#173 #168 feat map screen marker upgrade
  lib/core/domain/photo_cluster_item.dart
  lib/presentation/component/custom_map_marker.dart
  lib/presentation/component/map_bottom_sheet.dart
  lib/presentation/component/photopin_map.dart
  lib/presentation/component/trip_with_chips.dart
  lib/presentation/screen/map/map_screen.dart
  pubspec.yaml
  test/presentation/component/map_bottom_sheet_test.dart
  test/presentation/component/photo_map_test.dart
Labels: feature

#176 #174 feat deep link
  android/app/src/main/AndroidManifest.xml
  lib/core/router.dart
Labels: feature

#179 #177 refactor journals return stream
  lib/core/di/di_setup.dart
  lib/core/usecase/watch_journals_use_case.dart
  lib/journal/data/data_source/journal_data_source.dart
  lib/journal/data/data_source/journal_data_source_impl.dart
  lib/journal/data/repository/journal_repository.dart
  lib/journal/data/repository/journal_repository_impl.dart
  lib/presentation/screen/home/home_view_model.dart
  lib/presentation/screen/journal/journal_view_model.dart
  test/journal/screen/journal_screen_view_model_test.dart
  test/presentation/screen/home/home_view_model_test.dart
Labels: refactor

#178 #169 fire storage emulator 연동, #171 카메라 스크린 리팩터
  .gitignore
  analysis_options.yaml
  assets/base
  firebase.json
  firebase_device.json
  lib/core/di/di_setup.dart
  lib/core/domain/binary_data.dart
  lib/core/enums/camera_stream_event.dart
  lib/core/enums/image_mime.dart
  lib/core/enums/permission_type.dart
  lib/core/router.dart
  lib/core/usecase/get_place_name_use_case.dart
  lib/core/usecase/launch_camera_use_case.dart
  lib/core/usecase/permission_checker_use_case.dart
  lib/core/usecase/save_photo_use_case.dart
  lib/core/usecase/upload_file_use_case.dart
  lib/firebase_options.dart
  lib/main_dev.dart
  lib/photo/data/data_source/photo_data_source_impl.dart
  lib/photo/data/repository/photo_repository_impl.dart
  lib/presentation/screen/camera/camera_launcher_screen.dart
  lib/presentation/screen/camera/camera_launcher_screen_root.dart
  lib/presentation/screen/camera/camera_state.dart
  lib/presentation/screen/camera/camera_view_model.dart
  lib/presentation/screen/camera/handler/camera_handler.dart
  lib/presentation/screen/camera/handler/image_picker_camera_handler.dart
  lib/presentation/screen/camera/handler/image_save_handler.dart
  lib/presentation/screen/camera/handler/image_save_plus_handler.dart
  lib/presentation/screen/camera/handler/permission_checker.dart
  lib/presentation/screen/camera/handler/permisson_handler_checker.dart
  lib/storage/data/data_source/firebase_storage_data_source.dart
  lib/storage/data/data_source/storage_data_source.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  saved-data/auth_export/accounts.json
  saved-data/firebase-export-metadata.json
  saved-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  saved-data/firestore_export/all_namespaces/all_kinds/output-0
  saved-data/firestore_export/firestore_export.overall_export_metadata
  saved-data/storage_export/buckets.json
  storage.rules
  test/photo/data/repository/photo_repository_test.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feature

#184 #180 feat setting screen
  lib/core/di/di_setup.dart
  lib/core/router.dart
  lib/core/routes.dart
  lib/presentation/screen/main/main_screen.dart
  lib/presentation/screen/settings/settings_action.dart
  lib/presentation/screen/settings/settings_screen.dart
  lib/presentation/screen/settings/settings_screen_root.dart
  lib/presentation/screen/settings/settings_view_model.dart
  test/presentation/screen/settings/settings_view_model_test.dart
Labels: feature

#191 #189 refactor CameraViewModel
  lib/camera/data/repository/image_save_plus_local_device_repository.dart
  lib/camera/data/repository/local_device_repository.dart
  lib/camera/helper/camera_helper.dart
  lib/camera/helper/image_picker_camera_helper.dart
  lib/camera/presentation/camera_launcher_screen_root.dart
  lib/camera/presentation/camera_view_model.dart
  lib/camera/usecase/launch_camera_check_permission_use_case.dart
  lib/camera/usecase/launch_camera_use_case.dart
  lib/camera/usecase/save_picture_in_device_use_case.dart
  lib/camera/usecase/save_picture_in_firebase_use_case.dart
  lib/core/di/di_setup.dart
  lib/core/domain/binary_data.dart
  lib/core/domain/image_data.dart
  lib/core/domain/location.dart
  lib/core/enums/permission_allow_status.dart
  lib/core/router.dart
  lib/core/service/geolocator_location_service.dart
  lib/core/service/location_service.dart
  lib/core/usecase/get_current_location_use_case.dart
  lib/core/usecase/get_place_name_use_case.dart
  lib/core/usecase/launch_camera_use_case.dart
  lib/core/usecase/permission_check_use_case.dart
  lib/core/usecase/permission_checker_use_case.dart
  lib/core/usecase/upload_file_in_storage_use_case.dart
  lib/presentation/screen/camera/camera_state.dart
  lib/presentation/screen/camera/camera_view_model.dart
  lib/presentation/screen/camera/handler/camera_handler.dart
  lib/presentation/screen/camera/handler/image_picker_camera_handler.dart
  lib/presentation/screen/camera/handler/image_save_handler.dart
  lib/presentation/screen/camera/handler/image_save_plus_handler.dart
  lib/presentation/screen/camera/handler/permission_checker.dart
  lib/presentation/screen/camera/handler/permisson_handler_checker.dart
  lib/presentation/screen/settings/settings_view_model.dart
Labels: refactor

#194 #185 feat compare map
  lib/core/di/di_setup.dart
  lib/core/domain/integration_model.dart
  lib/core/router.dart
  lib/core/routes.dart
  lib/core/usecase/get_compare_model_use_case.dart
  lib/presentation/component/compare_card.dart
  lib/presentation/component/custom_map_marker.dart
  lib/presentation/component/grouplist_photos_timeline_tile.dart
  lib/presentation/component/photopin_map.dart
  lib/presentation/component/select_journal_modal.dart
  lib/presentation/component/trip_with_chips.dart
  lib/presentation/screen/compare_dialog/compare_dialog_action.dart
  lib/presentation/screen/compare_dialog/compare_dialog_screen.dart
  lib/presentation/screen/compare_dialog/compare_dialog_screen_root.dart
  lib/presentation/screen/compare_dialog/compare_dialog_state.dart
  lib/presentation/screen/compare_dialog/compare_dialog_view_model.dart
  lib/presentation/screen/compare_map/compare_map_action.dart
  lib/presentation/screen/compare_map/compare_map_screen.dart
  lib/presentation/screen/compare_map/compare_map_screen_root.dart
  lib/presentation/screen/compare_map/compare_map_state.dart
  lib/presentation/screen/compare_map/compare_map_view_model.dart
  lib/presentation/screen/home/home_screen_root.dart
  lib/presentation/screen/journal/journal_screen_root.dart
  lib/presentation/screen/map/map_screen.dart
  test/presentation/component/compare_card_test.dart
Labels: feature

#211 #210 refactor map screen compare map screen bottom sheet modify
  lib/presentation/component/move_bottom_sheet.dart
  lib/presentation/screen/compare_map/compare_map_screen.dart
  lib/presentation/screen/map/map_screen.dart
Labels: refactor

#209 #208 feat map screen share
  lib/core/router.dart
  lib/presentation/screen/map/map_action.dart
  lib/presentation/screen/map/map_screen.dart
  lib/presentation/screen/map/map_screen_root.dart
  lib/presentation/screen/map/map_view_model.dart
Labels: feature

#213 #212 refactor map screen google map component
  lib/core/di/di_setup.dart
  lib/core/domain/integration_model.dart
  lib/core/router.dart
  lib/presentation/component/integration_map.dart
  lib/presentation/screen/compare_map/compare_map_screen.dart
  lib/presentation/screen/map/map_screen.dart
  lib/presentation/screen/map/map_screen_root.dart
  lib/presentation/screen/map/map_state.dart
  lib/presentation/screen/map/map_view_model.dart
Labels: refactor

#214 #202 journal edit bottom sheet
  README.md
  analysis_options.yaml
  lib/camera/presentation/camera_view_model.dart
  lib/core/di/di_setup.dart
  lib/core/usecase/update_journal_use_case.dart
  lib/journal/data/data_source/journal_data_source.dart
  lib/journal/data/data_source/journal_data_source_impl.dart
  lib/journal/data/dto/journal_dto.dart
  lib/journal/data/repository/journal_repository.dart
  lib/journal/data/repository/journal_repository_impl.dart
  lib/presentation/component/edit_bottom_sheet.dart
  lib/presentation/component/journal_card.dart
  lib/presentation/component/journal_edit_bottom_sheet.dart
  lib/presentation/component/new_journal_modal.dart
  lib/presentation/component/text_limit_input_field.dart
  lib/presentation/screen/journal/journal_screen.dart
  lib/presentation/screen/journal/journal_screen_action.dart
  lib/presentation/screen/journal/journal_screen_root.dart
  lib/presentation/screen/journal/journal_view_model.dart
  lib/presentation/screen/photos/photos_screen.dart
  test/journal/screen/journal_screen_view_model_test.dart
  test/presentation/component/journal_card_test.dart
  test/presentation/component/journal_edit_bottom_sheet_test.dart
Labels: feature

#220 #187 feat fcm
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable/photopin_icon.png
  firebase.json
  functions/.eslintrc.js
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
  lib/core/di/di_setup.dart
  lib/core/enums/permission_type.dart
  lib/core/router.dart
  lib/core/service/push_service.dart
  lib/core/usecase/link_access_notification_use_case.dart
  lib/core/usecase/permission_check_use_case.dart
  lib/core/usecase/save_token_use_case.dart
  lib/fcm/data/data_source/firebase_messaging_data_source.dart
  lib/fcm/data/data_source/firebase_messaging_data_source_impl.dart
  lib/fcm/data/repository/token_repository.dart
  lib/fcm/data/repository/token_repository_impl.dart
  lib/main_dev.dart
  lib/presentation/screen/auth/auth_screen_root.dart
  lib/presentation/screen/auth/auth_view_model.dart
  lib/presentation/screen/compare_dialog/compare_dialog_view_model.dart
  lib/presentation/screen/home/home_view_model.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  package.json
  pubspec.lock
  pubspec.yaml
  saved-data/auth_export/accounts.json
  saved-data/firebase-export-metadata.json
  saved-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  test/presentation/screen/auth/auth_view_model_test.dart
  test/presentation/screen/home/home_view_model_test.dart
  windows/flutter/generated_plugins.cmake
Labels: feature

#215 #200 #205 journals screen
  lib/core/debouncer.dart
  lib/core/di/di_setup.dart
  lib/core/enums/search_filter_option.dart
  lib/core/extensions/datetime_range_extension.dart
  lib/core/usecase/search_journal_by_date_time_range_use_case.dart
  lib/core/usecase/watch_journals_use_case.dart
  lib/journal/data/data_source/journal_data_source.dart
  lib/journal/data/data_source/journal_data_source_impl.dart
  lib/journal/data/repository/journal_repository.dart
  lib/journal/data/repository/journal_repository_impl.dart
  lib/presentation/component/journal_edit_bottom_sheet.dart
  lib/presentation/component/search_bar.dart
  lib/presentation/component/search_filter_bottom_sheet.dart
  lib/presentation/screen/journal/journal_screen.dart
  lib/presentation/screen/journal/journal_screen_action.dart
  lib/presentation/screen/journal/journal_screen_root.dart
  lib/presentation/screen/journal/journal_state.dart
  lib/presentation/screen/journal/journal_view_model.dart
  test/journal/screen/journal_screen_view_model_test.dart
  test/presentation/component/search_bar_test.dart
Labels: bug, feature

#217 #216 hotfix login after save
  lib/auth/data/data_source/auth_data_source.dart
  lib/auth/data/data_source/auth_data_source_impl.dart
  lib/auth/data/repository/auth_repository.dart
  lib/auth/data/repository/auth_repository_impl.dart
  lib/core/di/di_setup.dart
  lib/core/usecase/auth_and_user_save_use_case.dart
  lib/presentation/screen/auth/auth_view_model.dart
  lib/user/data/data_source/user_data_source_impl.dart
  lib/user/data/mapper/user_mapper.dart
  lib/user/data/repository/user_repository.dart
  lib/user/data/repository/user_repository_impl.dart
  test/auth/data/data_source/fake_auth_data_source.dart
  test/presentation/screen/auth/auth_view_model_test.dart
Labels: hotfix

#219 #218 refactor: 비교 맵 화면이 아닐 경우 처음 photo에 포커스되게 변경
  lib/presentation/component/integration_map.dart
Labels: refactor

#223 #222 Journal 삭제 기능 및 Journal Screen Stream으로 업데이트 된 데이터 반영
  lib/core/di/di_setup.dart
  lib/core/usecase/delete_journal_use_case.dart
  lib/core/usecase/watch_photo_collection_use_case.dart
  lib/presentation/component/confirm_dialog.dart
  lib/presentation/component/journal_edit_bottom_sheet.dart
  lib/presentation/screen/home/home_view_model.dart
  lib/presentation/screen/journal/journal_screen.dart
  lib/presentation/screen/journal/journal_screen_action.dart
  lib/presentation/screen/journal/journal_screen_root.dart
  lib/presentation/screen/journal/journal_view_model.dart
  test/journal/screen/journal_screen_view_model_test.dart
  test/presentation/component/journal_edit_bottom_sheet_test.dart
  test/presentation/screen/home/home_view_model_test.dart
Labels: feature

#226 # 206 feat photo screen bug fix
  lib/core/di/di_setup.dart
  lib/photo/data/repository/photo_repository_impl.dart
  lib/storage/data/data_source/firebase_storage_data_source.dart
  lib/storage/data/data_source/storage_data_source.dart
  test/photo/data/repository/fake_photo_data_source.dart
  test/photo/data/repository/fake_storage_data_source.dart
  test/photo/data/repository/photo_repository_test.dart
Labels: feature

#229 #refactor: date Range 당일치기 시간 에러 변경
  lib/presentation/component/date_range_slider.dart
  saved-data/auth_export/accounts.json
  saved-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  saved-data/firestore_export/all_namespaces/all_kinds/output-0
  saved-data/firestore_export/firestore_export.overall_export_metadata
Labels: refactor

#234 #230 feat: test data create
  saved-data/auth_export/accounts.json
  saved-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  saved-data/firestore_export/all_namespaces/all_kinds/output-0
  saved-data/firestore_export/firestore_export.overall_export_metadata
  saved-data/storage_export/blobs/006eca03-3003-4992-9bc7-de225b97906c
  saved-data/storage_export/blobs/024c5b91-326a-4de1-8d91-17f0b1828d84
  saved-data/storage_export/blobs/055e724b-4cb7-4aec-8183-1a9745bfe3da
  saved-data/storage_export/blobs/0cd15b91-39c8-41f5-b0dc-49ea32b95832
  saved-data/storage_export/blobs/0dedca25-9817-427d-976a-17994a9425d8
  saved-data/storage_export/blobs/2abc6470-795d-47d0-9902-fb6a845d0b87
  saved-data/storage_export/blobs/38e626e9-07a0-4a8b-aed4-d37f7600bd5b
  saved-data/storage_export/blobs/3c950dc7-1688-4fb4-b80e-1e5ab085e979
  saved-data/storage_export/blobs/4de296e6-4691-437f-ab88-724059a4e5ea
  saved-data/storage_export/blobs/54e1a2ba-10c2-4c4b-b537-db4c55ba06ed
  saved-data/storage_export/blobs/5d5f4578-5ed0-4f5b-b905-b8c9707155a5
  saved-data/storage_export/blobs/6d6f1318-772d-43a2-90ca-5fcd52544c99
  saved-data/storage_export/blobs/7b84a6b6-71e1-4c48-b5d7-d8d7d66432be
  saved-data/storage_export/blobs/9a3dc992-2310-47ba-99fb-306b8c1ec3a6
  saved-data/storage_export/blobs/a4ccf6cd-d141-4152-9982-77b30056fbb9
  saved-data/storage_export/blobs/a76c0bde-23e4-4efb-953a-26c4be20ccce
  saved-data/storage_export/blobs/d361158a-1f3c-47fb-bca3-d93f4676a43f
  saved-data/storage_export/blobs/eac05a8c-17d0-406d-a90b-4d2850299f60
  saved-data/storage_export/blobs/ff2577e1-b123-4b56-a65d-d59fa47e87be
  saved-data/storage_export/metadata/006eca03-3003-4992-9bc7-de225b97906c.json
  saved-data/storage_export/metadata/024c5b91-326a-4de1-8d91-17f0b1828d84.json
  saved-data/storage_export/metadata/055e724b-4cb7-4aec-8183-1a9745bfe3da.json
  saved-data/storage_export/metadata/0cd15b91-39c8-41f5-b0dc-49ea32b95832.json
  saved-data/storage_export/metadata/0dedca25-9817-427d-976a-17994a9425d8.json
  saved-data/storage_export/metadata/2abc6470-795d-47d0-9902-fb6a845d0b87.json
  saved-data/storage_export/metadata/38e626e9-07a0-4a8b-aed4-d37f7600bd5b.json
  saved-data/storage_export/metadata/3c950dc7-1688-4fb4-b80e-1e5ab085e979.json
  saved-data/storage_export/metadata/4de296e6-4691-437f-ab88-724059a4e5ea.json
  saved-data/storage_export/metadata/54e1a2ba-10c2-4c4b-b537-db4c55ba06ed.json
  saved-data/storage_export/metadata/5d5f4578-5ed0-4f5b-b905-b8c9707155a5.json
  saved-data/storage_export/metadata/6d6f1318-772d-43a2-90ca-5fcd52544c99.json
  saved-data/storage_export/metadata/7b84a6b6-71e1-4c48-b5d7-d8d7d66432be.json
  saved-data/storage_export/metadata/9a3dc992-2310-47ba-99fb-306b8c1ec3a6.json
  saved-data/storage_export/metadata/a4ccf6cd-d141-4152-9982-77b30056fbb9.json
  saved-data/storage_export/metadata/a76c0bde-23e4-4efb-953a-26c4be20ccce.json
  saved-data/storage_export/metadata/d361158a-1f3c-47fb-bca3-d93f4676a43f.json
  saved-data/storage_export/metadata/eac05a8c-17d0-406d-a90b-4d2850299f60.json
  saved-data/storage_export/metadata/ff2577e1-b123-4b56-a65d-d59fa47e87be.json
Labels: feature

#236 #235 feat: data add
  saved-data/auth_export/accounts.json
  saved-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  saved-data/firestore_export/all_namespaces/all_kinds/output-0
  saved-data/firestore_export/firestore_export.overall_export_metadata
  saved-data/storage_export/blobs/05aa6d68-b80c-468c-9992-ef5f5560b792
  saved-data/storage_export/blobs/1908232a-cfcb-4b1f-98c8-d878959fde34
  saved-data/storage_export/blobs/1f07f4dc-52a5-4e31-b1f4-3cf045eca8cd
  saved-data/storage_export/blobs/1fc01562-aa3c-4601-8b9d-c368877c05cb
  saved-data/storage_export/blobs/207c00fc-2e9a-4228-a0b3-4b7eab72a3c9
  saved-data/storage_export/blobs/2d836c15-00ee-4c26-8989-f770dc08c0eb
  saved-data/storage_export/blobs/33877f07-0143-4207-86e8-4837e73f91e7
  saved-data/storage_export/blobs/34d51217-8fc2-4b10-8970-38e8e4e7c0a9
  saved-data/storage_export/blobs/4e6f139e-d760-42cd-bcb2-b21e618ef079
  saved-data/storage_export/blobs/4f4a9795-2ce4-4a96-b833-292ffaf95d9b
  saved-data/storage_export/blobs/5e04c919-bfae-4590-b6c5-04314ca60655
  saved-data/storage_export/blobs/687ac44f-865a-4744-bf13-713a542bf890
  saved-data/storage_export/blobs/7f8c9d81-af6d-4dbf-9ad5-fce2b41c4b09
  saved-data/storage_export/blobs/84d780b8-1c7d-4ce4-8a49-b417e0601be5
  saved-data/storage_export/blobs/8de87f9d-2a7a-4b57-b2aa-abd18e5428a8
  saved-data/storage_export/blobs/9e0a0b42-2977-4dc2-9ab4-73d3b63fd4eb
  saved-data/storage_export/blobs/b2de0dbb-3b87-43f2-a160-45f7f7cf3db5
  saved-data/storage_export/blobs/b5b54155-1d66-4a6f-815f-8fc0cf479ab2
  saved-data/storage_export/blobs/b832b58a-d679-4c48-89b5-368a3ea50fbf
  saved-data/storage_export/blobs/c6975caf-fffe-4c23-a395-6761f33e2316
  saved-data/storage_export/blobs/d74f328d-063f-43be-ae3d-13cd46d0877b
  saved-data/storage_export/blobs/d8d7d53b-1e23-4c2f-bb97-27cf3a49d981
  saved-data/storage_export/blobs/da5ccb3b-9c9c-47f6-a388-9fb14fba3197
  saved-data/storage_export/metadata/05aa6d68-b80c-468c-9992-ef5f5560b792.json
  saved-data/storage_export/metadata/1908232a-cfcb-4b1f-98c8-d878959fde34.json
  saved-data/storage_export/metadata/1f07f4dc-52a5-4e31-b1f4-3cf045eca8cd.json
  saved-data/storage_export/metadata/1fc01562-aa3c-4601-8b9d-c368877c05cb.json
  saved-data/storage_export/metadata/207c00fc-2e9a-4228-a0b3-4b7eab72a3c9.json
  saved-data/storage_export/metadata/2d836c15-00ee-4c26-8989-f770dc08c0eb.json
  saved-data/storage_export/metadata/33877f07-0143-4207-86e8-4837e73f91e7.json
  saved-data/storage_export/metadata/34d51217-8fc2-4b10-8970-38e8e4e7c0a9.json
  saved-data/storage_export/metadata/4e6f139e-d760-42cd-bcb2-b21e618ef079.json
  saved-data/storage_export/metadata/4f4a9795-2ce4-4a96-b833-292ffaf95d9b.json
  saved-data/storage_export/metadata/5e04c919-bfae-4590-b6c5-04314ca60655.json
  saved-data/storage_export/metadata/687ac44f-865a-4744-bf13-713a542bf890.json
  saved-data/storage_export/metadata/7f8c9d81-af6d-4dbf-9ad5-fce2b41c4b09.json
  saved-data/storage_export/metadata/84d780b8-1c7d-4ce4-8a49-b417e0601be5.json
  saved-data/storage_export/metadata/8de87f9d-2a7a-4b57-b2aa-abd18e5428a8.json
  saved-data/storage_export/metadata/9e0a0b42-2977-4dc2-9ab4-73d3b63fd4eb.json
  saved-data/storage_export/metadata/b2de0dbb-3b87-43f2-a160-45f7f7cf3db5.json
  saved-data/storage_export/metadata/b5b54155-1d66-4a6f-815f-8fc0cf479ab2.json
  saved-data/storage_export/metadata/b832b58a-d679-4c48-89b5-368a3ea50fbf.json
  saved-data/storage_export/metadata/c6975caf-fffe-4c23-a395-6761f33e2316.json
  saved-data/storage_export/metadata/d74f328d-063f-43be-ae3d-13cd46d0877b.json
  saved-data/storage_export/metadata/d8d7d53b-1e23-4c2f-bb97-27cf3a49d981.json
  saved-data/storage_export/metadata/da5ccb3b-9c9c-47f6-a388-9fb14fba3197.json
Labels: feature

#241 #240 refactor journal modify create event
  lib/core/enums/error_type.dart
  lib/presentation/component/new_journal_modal.dart
  lib/presentation/screen/home/home_screen_root.dart
Labels: refactor

#238 #237 refactor timeline tile color change icon
  lib/presentation/component/timeline_tile.dart
  lib/presentation/screen/compare_dialog/compare_dialog_screen_root.dart
  test/presentation/component/timeline_tile_test.dart
Labels: refactor

#245 #242 feat journal이 변경되었을 때만 서버에 변경 요청 전달
  lib/journal/domain/model/journal_model.dart
  lib/presentation/component/journal_edit_bottom_sheet.dart
  lib/presentation/screen/journal/journal_screen.dart
  test/presentation/component/journal_edit_bottom_sheet_test.dart
Labels: feature

#244 #225 feat dropdown modify
  lib/presentation/component/photo_edit_bottom_sheet.dart
  lib/presentation/screen/photos/photos_screen.dart
Labels: feature

#250 #243 feat advertisement component
  assets/images/gupae.png
  lib/presentation/component/banner_ad.dart
  lib/presentation/screen/home/home_screen.dart
  pubspec.yaml
  saved-data/auth_export/accounts.json
  saved-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  saved-data/firestore_export/all_namespaces/all_kinds/output-0
  saved-data/firestore_export/firestore_export.overall_export_metadata
  saved-data/storage_export/blobs/0eea8a66-35ab-49c9-8414-bc69f8732cd5
  saved-data/storage_export/blobs/236592ee-4818-4420-9e76-19a3181bac69
  saved-data/storage_export/blobs/2516f6ad-fb31-44b5-bc82-19c06ef63891
  saved-data/storage_export/blobs/25c6cdbd-4780-4248-8da3-406aa60ad730
  saved-data/storage_export/blobs/3d23b201-06c7-435d-ab93-3dc91c79a56b
  saved-data/storage_export/blobs/428f7392-6f34-48f1-ac5d-f433ae5c59d0
  saved-data/storage_export/blobs/43ef7449-74ec-4219-b8b1-c94ecd5b320a
  saved-data/storage_export/blobs/48cd9bec-6a89-4c7e-8ad5-b3e2e184ba3e
  saved-data/storage_export/blobs/4a3669b1-a8ed-4497-8476-102ce767cf0a
  saved-data/storage_export/blobs/5fe0140b-a466-489a-a4d4-d5abc10cf55e
  saved-data/storage_export/blobs/5ff85435-dc97-4f98-a64a-131f3e77c904
  saved-data/storage_export/blobs/662f96eb-63d5-4edf-9806-190249da401d
  saved-data/storage_export/blobs/69f8c7b0-02e8-4c6a-b367-87a2974c155a
  saved-data/storage_export/blobs/6f347fa4-4f4e-44cc-99bc-df49e2fa30a8
  saved-data/storage_export/blobs/7180f69f-8c0b-4c1e-9807-109071eb0c75
  saved-data/storage_export/blobs/9db2d114-8609-4d4a-9834-b8af7359ac7b
  saved-data/storage_export/blobs/a818ef39-8368-4119-806e-d90363097808
  saved-data/storage_export/blobs/a8ed1eb4-c70f-4c87-b08c-e818152cd7f3
  saved-data/storage_export/blobs/aaf5dfed-06e0-4a2e-8b26-9363b94f68d2
  saved-data/storage_export/blobs/cde343a2-76d8-43ae-bd81-583baa6611ca
  saved-data/storage_export/blobs/e5ba3f53-2348-4c4e-8dc0-90e70cba3961
  saved-data/storage_export/blobs/fe57398f-67ad-4e81-a457-abecf6bd7714
  saved-data/storage_export/blobs/ff3861c3-61d1-41a9-a1f4-8ac0966be76f
  saved-data/storage_export/metadata/0eea8a66-35ab-49c9-8414-bc69f8732cd5.json
  saved-data/storage_export/metadata/236592ee-4818-4420-9e76-19a3181bac69.json
  saved-data/storage_export/metadata/2516f6ad-fb31-44b5-bc82-19c06ef63891.json
  saved-data/storage_export/metadata/25c6cdbd-4780-4248-8da3-406aa60ad730.json
  saved-data/storage_export/metadata/3d23b201-06c7-435d-ab93-3dc91c79a56b.json
  saved-data/storage_export/metadata/428f7392-6f34-48f1-ac5d-f433ae5c59d0.json
  saved-data/storage_export/metadata/43ef7449-74ec-4219-b8b1-c94ecd5b320a.json
  saved-data/storage_export/metadata/48cd9bec-6a89-4c7e-8ad5-b3e2e184ba3e.json
  saved-data/storage_export/metadata/4a3669b1-a8ed-4497-8476-102ce767cf0a.json
  saved-data/storage_export/metadata/5fe0140b-a466-489a-a4d4-d5abc10cf55e.json
  saved-data/storage_export/metadata/5ff85435-dc97-4f98-a64a-131f3e77c904.json
  saved-data/storage_export/metadata/662f96eb-63d5-4edf-9806-190249da401d.json
  saved-data/storage_export/metadata/69f8c7b0-02e8-4c6a-b367-87a2974c155a.json
  saved-data/storage_export/metadata/6f347fa4-4f4e-44cc-99bc-df49e2fa30a8.json
  saved-data/storage_export/metadata/7180f69f-8c0b-4c1e-9807-109071eb0c75.json
  saved-data/storage_export/metadata/9db2d114-8609-4d4a-9834-b8af7359ac7b.json
  saved-data/storage_export/metadata/a818ef39-8368-4119-806e-d90363097808.json
  saved-data/storage_export/metadata/a8ed1eb4-c70f-4c87-b08c-e818152cd7f3.json
  saved-data/storage_export/metadata/aaf5dfed-06e0-4a2e-8b26-9363b94f68d2.json
  saved-data/storage_export/metadata/cde343a2-76d8-43ae-bd81-583baa6611ca.json
  saved-data/storage_export/metadata/e5ba3f53-2348-4c4e-8dc0-90e70cba3961.json
  saved-data/storage_export/metadata/fe57398f-67ad-4e81-a457-abecf6bd7714.json
  saved-data/storage_export/metadata/ff3861c3-61d1-41a9-a1f4-8ac0966be76f.json
Labels: feature

#251 #201 bug setting screen
  lib/presentation/screen/settings/settings_screen_root.dart
  lib/presentation/screen/settings/settings_view_model.dart
Labels: feature

#252 # 249 feat auth screen modify
  assets/images/google_logo.webp
  assets/images/photopin.png
  assets/images/trip.jpg
  lib/core/di/di_setup.dart
  lib/photo/data/data_source/photo_data_source_impl.dart
  lib/presentation/screen/auth/auth_screen.dart
  lib/presentation/screen/settings/settings_screen.dart
  lib/presentation/screen/settings/settings_screen_root.dart
  lib/presentation/screen/settings/settings_view_model.dart
  pubspec.lock
Labels: feature
